name: License Compliance

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  license-check:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-nodejs-licence-analysis.yml@nodejs
    with:
      node-version: '19.5.0'
      java-version: '17'
      create-review: true
    secrets:
      token: ${{ secrets.GITLAB_API_TOKEN }}